# -*- coding: utf-8 -*-
"""Mendelson_Pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxTJkxeAiRC5nGKTc6iU5mTAC-n19uES
"""

# Import  libraries
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load dataset
pokemon_data = pd.read_csv("pokemons.csv")

# Set Seaborn grid theme
sns.set_theme(style="whitegrid")

# Adjust default font size for better readability
plt.rcParams.update({'font.size': 12})

# 1. Boxplot: Comparing total stats across generations
plt.figure(figsize=(12, 6))
sns.boxplot(x='generation', y='total', data=pokemon_data, palette='Set3')
# Modify x-axis labels to "Gen 1", "Gen 2", etc.
plt.title('Boxplot of Total Stats by Generation', fontsize=16)
plt.xlabel('Generation', fontsize=14)
plt.ylabel('Total Stats', fontsize=14)
plt.xticks(ticks=[0, 1, 2, 3, 4, 5, 6, 7], labels=['Gen 1', 'Gen 2', 'Gen 3', 'Gen 4', 'Gen 5', 'Gen 6', 'Gen 7', 'Gen 8'], fontsize=12)
plt.yticks(fontsize=12)
plt.show()

# 2. Violin Plot: Distribution of Attack Power by Primary Type
plt.figure(figsize=(14, 7))
sns.violinplot(x='type1', y='atk', data=pokemon_data, palette='rainbow')
plt.title('Violin Plot of Attack Power by Primary Type', fontsize=16)
plt.xlabel('Primary Type', fontsize=14)
plt.ylabel('Attack Power', fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.show()

# 3. Swarm Plot: Showing Defense stat grouped by Primary Type
plt.figure(figsize=(14, 7))
sns.swarmplot(x='type1', y='def', data=pokemon_data, palette='Set2')
plt.title('Swarm Plot of Defense by Primary Type', fontsize=16)
plt.xlabel('Primary Type', fontsize=14)
plt.ylabel('Defense', fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.show()

# 4. Barplot: Average Speed of Pokémon by Primary Type (Replaces Pairplot for variety)
plt.figure(figsize=(12, 6))
type_speed = pokemon_data.groupby('type1')['speed'].mean().reset_index()
sns.barplot(x='type1', y='speed', data=type_speed, palette='coolwarm')
plt.title('Average Speed by Primary Pokémon Type', fontsize=16)
plt.xlabel('Primary Type', fontsize=14)
plt.ylabel('Average Speed', fontsize=14)
plt.xticks(rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.show()